java_test(
  name = 'nullTest',
  srcs = ['NullTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen/simulation:simulation' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen/simulation:simulation',
    '//libs:mason',
  ],
)

java_test(
  name = 'personTest',
  srcs = ['PersonTest.java'],
  source_under_test = [ '//java/org/denovogroup/rangzen/simulation:simulation' ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:junit-4.11',
    '//libs:hamcrest-core-1.3',
    '//java/org/denovogroup/rangzen/simulation:simulation',
    '//libs:mason',
  ],
)
