prebuilt_jar(
  name = 'mason',
  binary_jar = 'mason.17.jar', 
  visibility = [ 'PUBLIC' ],
)

prebuilt_jar(
  name = 'junit-4.11',
  binary_jar = 'junit-4.11.jar', 
  visibility = [ 'PUBLIC' ],
)

prebuilt_jar(
  name = 'hamcrest-core-1.3',
  binary_jar = 'hamcrest-core-1.3.jar', 
  visibility = [ 'PUBLIC' ],
)

