java_library(
  name = 'simulation',
  srcs = [ 'Message.java', 'Person.java', 
           'MessagePropagationSimulation.java', 'MessagePropagationSimulationWithGUI.java',
           'ProximityEncounterModel.java', 'SimpleEncounterModel.java', ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:mason',
  ],
)
