java_library(
  name = 'simulation',
  srcs = [ 'Message.java', 'Person.java', 'Location.java', 'MobilityTrace.java',
           'MessagePropagationSimulation.java', 
           'ProximitySimulationWithGUI.java',
           'ProximityEncounterModel.java', 'SimpleEncounterModel.java', 
           'ProximitySimulation.java', 
           'SingleMessageTrackingMeasurer.java', 'StAndrewsSocialNetworkParser.java', ],
  visibility = [ 'PUBLIC' ],
  deps = [
    '//libs:jcoord',
    '//libs:mason',
    '//libs:opencsv',
    '//libs:gson',
  ],
)
